### ISSUE TITLE
Be specific about the data format version

### ISSUE THREAD

**Issue by grahamegrieve** [CMSgov/bcda-app#185]
The documentation is not specific about which version of FHIR or blue button is in use (nor does it link explicitly to the blue button documentation so far as I could see). This information would be useful here (rather than having to guess it from elsewhere) - thanks

**Comment by rnagle** [comment]
Hi @grahamegrieve , thanks for bringing this to our attention. We've created a ticket in our internal tracking system for this issue. Don't have an ETA for resolution, but recognize this is important.

In the meantime, for folks that are looking for this information, BCDA is supported by the Blue Button FHIR service, which currently supports FHIR v3. You can find the implementation guide here: https://bluebutton.cms.gov/assets/ig/index.html

For anyone that has access to our internal task tracker, the issue can be found here: https://jira.cms.gov/browse/BCDA-952

We'll update this issue as it makes it's way through our workflow. Thanks again. 👍
