### ISSUE TITLE
BCDA's OAuth Token Response has String expires_in

### ISSUE THREAD

**Issue by suyashkumar** [CMSgov/bcda-app#806]
Hi there! I noticed that BCDA's OAuth Token response provides a string value for the `expires_in` parameter. 

If I'm reading the [OAuth RFC correctly](https://www.rfc-editor.org/rfc/rfc6749#appendix-A.14), expires_in should be a numeric value instead of a string value (e.g. not quoted in JSON).  

Functionally what that means is that expiresIn needs to be returned as a numeric here: https://github.com/CMSgov/bcda-app/blob/5a35685fe21354972d7a966082e4b15aa2e411ee/bcda/auth/api.go#L44.

Let me know if I can help.

Cheers,
-Suyash

**Comment by carlpartridge** [comment]
Seems like this issue was resolved but not closed, closing now.
